import type { OutputFile, RepoInsight, RiskSignal, ScriptCommand } from "./types.js";

export function generateOutputs(insight: RepoInsight, format: "markdown" | "json"): OutputFile[] {
  if (format === "json") {
    return [
      {
        filename: "repo-context.json",
        content: `${JSON.stringify(insight, null, 2)}\n`
      }
    ];
  }

  return [
    { filename: "AGENTS.md", content: generateAgentsMd(insight) },
    { filename: "agent-brief.md", content: generateAgentBrief(insight) },
    { filename: "commands.md", content: generateCommands(insight) },
    { filename: "repo-map.md", content: generateRepoMap(insight) },
    { filename: "risk-report.md", content: generateRiskReport(insight) }
  ];
}

function generateAgentsMd(insight: RepoInsight): string {
  return `${frontMatter(insight)}
# AGENTS.md

This file was generated by \`repo-context-pack\` to help coding agents enter this repository safely and quickly.

## Repository Snapshot

- Repository: \`${insight.repoName}\`
- Package manager: \`${insight.packageManager}\`
- Primary languages: ${formatLanguages(insight)}
- Detected frameworks: ${formatListInline(insight.frameworks)}
- Scan size: ${insight.totalFiles} files${insight.truncated ? " (truncated)" : ""}

## Working Rules For Agents

1. Read this file, \`agent-brief.md\`, \`repo-map.md\`, and \`commands.md\` before editing.
2. Do not run commands marked high risk without explicit human approval.
3. Do not read or quote local secret files such as \`.env\`; use redacted examples only.
4. Prefer the existing package manager and scripts listed below.
5. Keep changes scoped and add verification evidence in your final response.

## First Files To Inspect

${formatBulletList([...insight.entrypoints, ...insight.configFiles].slice(0, 20), "No obvious entrypoints or config files detected.")}

## Test And Verification Surface

${formatBulletList(insight.tests.slice(0, 20), "No obvious tests detected. Add or document a focused smoke test for meaningful changes.")}

## High-Risk Notes

${formatRiskBullets(insight.risks.filter((risk) => risk.severity === "high"))}
`;
}

function generateAgentBrief(insight: RepoInsight): string {
  const safeScripts = insight.scripts.filter((script) => script.risk !== "high");
  const highRiskScripts = insight.scripts.filter((script) => script.risk === "high");

  return `${frontMatter(insight)}
# Agent Brief

## What This Repository Appears To Be

${describeRepo(insight)}

## Likely Build System

- Package manager: \`${insight.packageManager}\`
- Frameworks/tools: ${formatListInline(insight.frameworks)}
- Config files: ${formatListInline(insight.configFiles.slice(0, 12))}

## Safe Starting Commands

${formatScriptTable(safeScripts.slice(0, 20), "No low-risk package scripts were detected.")}

## Commands That Need Human Approval

${formatScriptTable(highRiskScripts, "No high-risk package scripts were detected.")}

## Suggested First Agent Prompt

\`\`\`text
You are working in ${insight.repoName}. Read AGENTS.md, agent-brief.md, repo-map.md, and commands.md first. Follow the listed package manager and avoid high-risk commands unless I explicitly approve them. Make the smallest useful change, then report files changed and validation evidence.
\`\`\`
`;
}

function generateCommands(insight: RepoInsight): string {
  const grouped = groupScripts(insight.scripts);

  return `${frontMatter(insight)}
# Commands

These commands were discovered from package metadata. They have not been executed by \`repo-context-pack\`.

${Object.entries(grouped)
  .map(([category, scripts]) => `## ${titleCase(category)}\n\n${formatScriptTable(scripts, "None detected.")}`)
  .join("\n\n")}
`;
}

function generateRepoMap(insight: RepoInsight): string {
  return `${frontMatter(insight)}
# Repo Map

## Languages

${formatLanguageTable(insight)}

## Entrypoints

${formatBulletList(insight.entrypoints, "No obvious entrypoints detected.")}

## Configuration

${formatBulletList(insight.configFiles, "No common config files detected.")}

## Documentation

${formatBulletList(insight.docs.slice(0, 40), "No common docs detected.")}

## Top-Level Shape

${formatTree(insight)}

## Ignored During Scan

${formatBulletList(insight.ignoredDirs.slice(0, 40), "No standard generated directories were encountered.")}
`;
}

function generateRiskReport(insight: RepoInsight): string {
  return `${frontMatter(insight)}
# Risk Report

This is a conservative static review. It is meant to guide agent behavior, not replace human review.

## Findings

${formatRiskTable(insight.risks)}

## Default Agent Safety Policy

- Treat high-risk commands as approval-gated.
- Do not paste secret files into prompts or generated reports.
- When tests are absent, require a manual smoke-test note.
- When the scan is truncated, ask for a larger context scan before major refactors.
`;
}

function frontMatter(insight: RepoInsight): string {
  return `<!-- Generated by repo-context-pack at ${insight.generatedAt}. Source: ${insight.repoRoot} -->`;
}

function describeRepo(insight: RepoInsight): string {
  const language = insight.languages[0]?.name ?? "unknown language";
  const frameworks = insight.frameworks.length > 0 ? ` using ${insight.frameworks.join(", ")}` : "";
  const tests =
    insight.tests.length > 0
      ? `It has ${insight.tests.length} obvious test-related files.`
      : "No obvious test files were detected.";
  const docs =
    insight.docs.length > 0
      ? `Documentation exists in ${insight.docs.slice(0, 5).map((item) => `\`${item}\``).join(", ")}.`
      : "No common documentation files were detected.";

  return `This looks like a ${language}-heavy repository${frameworks}. ${tests} ${docs}`;
}

function formatLanguages(insight: RepoInsight): string {
  if (insight.languages.length === 0) return "unknown";
  return insight.languages
    .slice(0, 4)
    .map((language) => `${language.name} ${language.percent}%`)
    .join(", ");
}

function formatListInline(items: string[]): string {
  if (items.length === 0) return "none detected";
  return items.map((item) => `\`${item}\``).join(", ");
}

function formatBulletList(items: string[], emptyMessage: string): string {
  if (items.length === 0) return `- ${emptyMessage}`;
  return items.map((item) => `- \`${item}\``).join("\n");
}

function formatRiskBullets(risks: RiskSignal[]): string {
  if (risks.length === 0) return "- No high-risk signals detected.";
  return risks
    .map((risk) => `- **${risk.title}** (${risk.severity}): ${risk.evidence}. ${risk.recommendation}`)
    .join("\n");
}

function formatScriptTable(scripts: ScriptCommand[], emptyMessage: string): string {
  if (scripts.length === 0) return emptyMessage;

  const rows = scripts.map((script) => {
    const notes = script.notes.length > 0 ? script.notes.join("; ") : "";
    return `| \`${script.name}\` | \`${escapePipes(script.command)}\` | ${script.risk} | ${notes} |`;
  });

  return ["| Script | Command | Risk | Notes |", "|---|---|---|---|", ...rows].join("\n");
}

function formatLanguageTable(insight: RepoInsight): string {
  if (insight.languages.length === 0) return "No language signals detected.";
  return [
    "| Language | Files | Share |",
    "|---|---:|---:|",
    ...insight.languages.map((language) => `| ${language.name} | ${language.files} | ${language.percent}% |`)
  ].join("\n");
}

function formatRiskTable(risks: RiskSignal[]): string {
  if (risks.length === 0) return "No risk signals detected by the static scan.";
  return [
    "| Severity | Finding | Evidence | Recommendation |",
    "|---|---|---|---|",
    ...risks.map(
      (risk) =>
        `| ${risk.severity} | ${risk.title} | ${escapePipes(risk.evidence)} | ${escapePipes(risk.recommendation)} |`
    )
  ].join("\n");
}

function groupScripts(scripts: ScriptCommand[]): Record<string, ScriptCommand[]> {
  const groups: Record<string, ScriptCommand[]> = {
    dev: [],
    build: [],
    test: [],
    lint: [],
    format: [],
    db: [],
    deploy: [],
    other: []
  };

  for (const script of scripts) {
    const group = groups[script.category];
    if (group) {
      group.push(script);
    }
  }

  return Object.fromEntries(Object.entries(groups).filter(([, value]) => value.length > 0));
}

function formatTree(insight: RepoInsight): string {
  const topLevel = new Map<string, { files: number; bytes: number }>();

  for (const file of insight.files) {
    const [head = file.path] = file.path.split("/");
    const current = topLevel.get(head) ?? { files: 0, bytes: 0 };
    current.files += 1;
    current.bytes += file.size;
    topLevel.set(head, current);
  }

  return [...topLevel.entries()]
    .sort((a, b) => b[1].files - a[1].files || a[0].localeCompare(b[0]))
    .slice(0, 40)
    .map(([name, stat]) => `- \`${name}\` - ${stat.files} files, ${formatBytes(stat.bytes)}`)
    .join("\n");
}

function formatBytes(bytes: number): string {
  if (bytes < 1024) return `${bytes} B`;
  if (bytes < 1024 * 1024) return `${Math.round(bytes / 1024)} KB`;
  return `${(bytes / 1024 / 1024).toFixed(1)} MB`;
}

function titleCase(value: string): string {
  return value.charAt(0).toUpperCase() + value.slice(1);
}

function escapePipes(value: string): string {
  return value.replaceAll("|", "\\|");
}
